version: "3.5"

services:
    web:
        build:
            context: ./services/web
        expose:
            - 5000
        ports:
            - 5000:5000
        volumes:
            - ./services/web:/app:ro
        command: /usr/local/bin/gunicorn -k gevent --reload --workers 1 --worker-connections 10 --timeout 30 --access-logfile=- --pythonpath /app -b :5000 app:app

    nginx:
        restart: always
        image: nginx:latest
        ports:
            - "8080:8080"
        volumes:
            - ./services/web/static:/www/static:ro
            - ./services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

